apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-minikube
  namespace: homework
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  storageClassName:  minikube-pv   