apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: homework
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 8000
          protocol: TCP
          name: http-web
      volumeMounts:
        - name: shared-data
          mountPath: /homework
        - name: config-volume
          mountPath: /etc/nginx
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm /homework/index.html"]
#### init-container ####
  initContainers:
    - name: init-container
      image: busybox
      volumeMounts:
        - name: shared-data
          mountPath: /init
      command: ["sh", "-c", "wget -O /init/index.html https://raw.githubusercontent.com/rayneadm/tings/main/web/index.html"]
  volumes:
    - name: config-volume
      configMap:
        name: nginx-config
    - name: shared-data
      emptyDir: {}